# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ans_sub',
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_sub',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.Submitter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quest_sub',
            field=models.ManyToManyField(to='vote.Submitter', verbose_name='Submitter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quest_text',
            field=models.CharField(max_length=200, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quest_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted On'),
        ),
    ]
