# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20160103_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ans_sub',
        ),
        migrations.AddField(
            model_name='answer',
            name='ans_sub',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.Submitter'),
        ),
    ]
