# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20160103_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_sub',
            field=models.CharField(default='admin', max_length=30, verbose_name='Submitter'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='quest_sub',
        ),
        migrations.AddField(
            model_name='question',
            name='quest_sub',
            field=models.CharField(default='admin', max_length=30, verbose_name='Submitter'),
        ),
        migrations.DeleteModel(
            name='Submitter',
        ),
    ]
