# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20160103_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ans_count',
            field=models.IntegerField(default=1),
        ),
    ]
